### ISSUE TITLE
スキーマ提案

### ISSUE THREAD

**Issue by t-hrhs** [zdogma/nyaran#1]
table1 : ranking_map
ランキングのidと実際のランキングテーブルを紐づけるテーブル
```
id (int) #各種ランキングの固有id
name (varchar) # ランキングの名前
media_type (int) # メディアの種類(サイトごと)
ranking_table (varchar) # ランキングのテーブル名(もしくはランキングテーブルのModel)
```
table2 : nico_hoge_ranking
nicoのhogeジャンルのランキングを管理するテーブル
(サービスやジャンルを増やすときはこのtableが増殖する)
```
rank (int) # 順位
score (int) # 評価値
distinct_str (varchar) # 各種動画を識別するuniqueなstring(apiを叩くときに利用)
created_at (int) レコードが作成されたタイミング(daily rankingの識別に利用)
```

**Comment by zdogma** [comment]
たたき台 thanks！

こうやって見てみると、
「あらゆるコンテンツのランキングをサクッと確認できるサービス」
ということは、source や category とかがかなり増えるイメージなんで、
その単位でテーブルが増殖していくのはちょっとつらいかなーと思いました。
（昼間の話からめっちゃ手のひら返しててごめん！）

といってもまだ明確に代替案があるわけではないんで、俺もちょっと考えてみます！

**Comment by zdogma** [comment]
下記みたいに引っ張れると良いのかなー。
でもこれ全コンテンツ取得前提だからデータ量やばそう。

```
# 形式
Ranking.{source}.{genre}.{aggregation_period}_ranks

# 具体例
Ranking.nicovideo.vocaloid.daily_ranks
Ranking.youtube.all_genre.lifetime_ranks
Ranking.pixiv.vocaloid.weekly_ranks
etc...
```

この場合は下記みたいな感じかしら。
```
* sources
  * id
  * media_type
  * name

# media_type の数だけテーブルがある
* movies
  * id
  * source_id
  * tags
  * name
  * thumbnail_url
  * view_count
  * etc...

* images

* ...
```

**Comment by zdogma** [comment]
今思ったけど、daily ranking とかって昨日と今日の差分ベースだから、
差分を取るために例えば daily で snapshot 的に API 叩く必要と、
そこから取り出した差分をテーブルに突っ込む必要があるんじゃないかという気がしてきた。。。

**Comment by t-hrhs** [comment]
> その単位でテーブルが増殖していくのはちょっとつらいかなーと思いました。
これはわかるのですが、全部まとめてしまうと各種ランキングで統一したカラムしか持てなくなってしまうけど、それでいいかいという懸念

> この場合は下記みたいな感じかしら。
あと、自分の想定は動画の固有識別id、動画タイトルとせいぜいサムネイル画像をこちらのサービス側で持って、あとは都度apiで取得だと思っていたけど違うのかな?
どこまでサービス側で動画の情報を保持しておくのか…

**Comment by zdogma** [comment]
動画情報をどこまで持つのかは要検討ではありんすが、
一旦nicovideo に絞ってできるだけAPIで取れる情報を突っ込んでみるのはどうだろう...w

あと、ランキングテーブル自体のスキーマは共通で良い気がする！
なぜならランキング詳細までは UI が同じになるはずだから！
（タイトル、サムネイル、URL、etc...）

**Comment by zdogma** [comment]
とりま新着ランキングでも作るか...

**Comment by t-hrhs** [comment]
設計指針は了解しました。
じゃあranking_tableは
・rank
・score
・distinct_str
・media_type
・genre
・created_at
これでどうかね。
あとは各種apiの情報をつめるのは
movie
media_type, distinct_str, movie_info(ここにapiの結果がごそっと入っているtext型)
で
parse_json, get_movieとか必要な情報を取得するメソッドをmedia_typeごとに定義すればいいんじゃね?

**Comment by zdogma** [comment]
※ id, timestamp2種(created_at, updated_at) はすべてに付く。
```
rankings
・id (int)
・name (string)
・is_public (boolean)
```
```
ranking_contents
・id (int)
・ranking_id (int)
・rank (int)
・score (int)
・distinct_code (string)
・source_media (int)
・media_type (int)
・genre (int)
```
media_type ごとにDBが分けられるイメージ。
```
movies
・id (int)
・distinct_code (string)
・source_media (string)
・api_response_json (text)
```

**Comment by t-hrhs** [comment]
LGTM

**Comment by zdogma** [comment]
rankings 1<~n ranking_contents n<~1 (contents: movies, photos, images, ... )

**Comment by zdogma** [comment]
上記の PR にて反映したので、閉じます！
