### ISSUE TITLE
Model提案

### ISSUE THREAD

**Issue by t-hrhs** [zdogma/nyaran#2]
RankingMap
ranking_mapテーブルに関するModel

Ranking/Base
rankingの親クラス
どの子クラスでも持つべきメソッドを定義(実態は子クラスに書く)
```
get_raw_datum_from_api (instance method)
=> 各種サービスのapiからデータを取得するメソッド(distinct_strを見る)
get_raw_data_from_batch (class method) ### for batch ###
=> 各種サービスのapiからバッチに必要なデータをまとめて取得するメソッド(top 10を計算するのに必要なデータを取得)
get_distinct_str (バッチでデータを取得あと、rankingのdistinctにどのキーの値をいれるべきか定義)
```
↑
ただ、これはここに本当はかきたくない(何かいい案あれば)

Ranking/NicoHoge(Ranking/Baseを継承)
上に書いた2つのメソッドを具体的にかく
(apiにどのパラメータなげて、どういう風にソートするか最後に整頓されたデータをごっそり返す)

**Comment by zdogma** [comment]
データを取ってくるのは Ranking の仕事というよりは Adaptor? 的な「APIとの連絡窓口」の役割かなーと思いますた。
Bridge パターンっぽい実装になるのは同意っす！

**Comment by zdogma** [comment]
```
nico = Adaptor::Nicovideo.new
movie = nico.fetch_data(movie_code)
```
的な？

**Comment by t-hrhs** [comment]
おお、Adapterという概念があるのか。これでお願いしますmm

**Comment by zdogma** [comment]
こっちも一通りコードに反映したので、一旦閉じます！
